### ISSUE TITLE
Improve fields creation

### ISSUE THREAD

**Issue by wilsonfreitas** [wilsonfreitas/rb3#27]
Fields have a handler attribute that defines the variable type to parse the column.
The pass-thru generic handler is to define handler type as character.
By doing that you tell to the parser that this column has not a specific type and should reaims as a character.

```yaml
fields:
- name: company
  description: Nome da companhia
  handler:
    type: character
```

Instead of defining a character handler a better approach is defining no handler. Like that:

```yaml
fields:
- name: company
  description: Nome da companhia
```
Once a field has no handler it is assumed it uses a pass-thru generic handler.

This simplifies the config file and improves configuration.
